### ISSUE TITLE
带鬼牌后，想要判断是否大胡，有什么好办法？（已完成清一色，七小对，还差碰碰胡）

### ISSUE THREAD

**Issue by liaolunhui** [yuanfengyun/qipai_algorithm#23]
清一色好判断，去除鬼牌，剩下的为同一种花色既为清一色。
七小对也好判断，去除鬼牌，去掉对子，剩余单牌数量等于鬼牌数量，即为清一色。
碰碰胡还没想到算法，求指点。

**Comment by yuanfengyun** [comment]
你再想想。

**Comment by chengsu** [comment]
碰碰胡直接作为标志位写到表里

**Comment by Jesse1205** [comment]
换成风牌判断吧

**Comment by qinggengemmm** [comment]
有没有好的想法，可以分享下吗

**Comment by yuanfengyun** [comment]
根据大胡的特点，每种大胡写一段代码来判断。这种没有通用规则的，最适合用代码来做，简单有效，而且效率很高。
